# Generated by Django 2.2 on 2019-04-10 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('price', models.FloatField()),
                ('rating', models.CharField(choices=[('1', '1점'), ('2', '2점'), ('3', '3점'), ('4', '4점'), ('5', '5점')], max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
